service: aws-learning
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  api:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /user
          method: post
  getUser:
    handler: src/handlers/getUser.handler
    events:
      - httpApi:
          path: /user/{id}
          method: get
  updateUser:
    handler: src/handlers/updateUser.handler
    events:
      - httpApi:
          path: /user/{id}
          method: put
  deleteUser:
    handler: src/handlers/deleteUser.handler
    events:
      - httpApi:
          path: /user/{id}
          method: delete

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
