service: aws-learning
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - aws-sdk
    target: node18
    platform: node
    concurrency: 10

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  httpApi:
    payload: '2.0'
    authorizers:
      cognitoAuth:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_eWj10lf1H
        audience:
          - 5e9v5dkfpjsnml27g3u25lu2qm

  environment:
    COGNITO_CLIENT_ID: 5e9v5dkfpjsnml27g3u25lu2qm
    COGNITO_USER_POOL_ID: us-east-1_eWj10lf1H
    USERS_TABLE: ${env:USERS_TABLE}
    SQS_USER_SIGNUP_QUEUE_URL:
      Ref: UserSignupQueue

  iamRoleStatements:

    # allow DynamoDB actions for user management
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

    # allow Cognito actions for signup and login
    - Effect: Allow
      Action:
        - cognito-idp:SignUp
        - cognito-idp:AdminConfirmSignUp
        - cognito-idp:InitiateAuth
        - cognito-idp:AdminDeleteUser
      Resource: "*"

    # Allow sending messages to SQS for user signup events
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        Fn::GetAtt:
          - UserSignupQueue
          - Arn

functions:

  # Public API (no auth)
  api:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /
          method: get

  # 🔓 SIGNUP (Public)
  signup:
    handler: src/handlers/auth/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post

  # 🔓 LOGIN (Public)
  login:
    handler: src/handlers/auth/login.handler
    events:
      - httpApi:
          path: /login
          method: post
  
  # 🔓 Me (Protected)
  getMe:
    handler: src/handlers/users/getMe.handler
    events:
      - httpApi:
          path: /me
          method: get
          authorizer:
            name: cognitoAuth
  
  # 🔓 Me (Protected)
  putMe:
    handler: src/handlers/users/putMe.handler
    events:
      - httpApi:
          path: /me
          method: put
          authorizer:
            name: cognitoAuth
  
  # 🔓 Me (Protected)
  deleteMe:
    handler: src/handlers/users/deleteMe.handler
    events:
      - httpApi:
          path: /me
          method: delete
          authorizer:
            name: cognitoAuth

  # CREATE (Protected)
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /user
          method: post
          authorizer:
            name: cognitoAuth

  # READ (Protected)
  getUser:
    handler: src/handlers/getUser.handler
    events:
      - httpApi:
          path: /user/{id}
          method: get
          authorizer:
            name: cognitoAuth
  
  # UPDATE (Protected)
  updateUser:
    handler: src/handlers/updateUser.handler
    events:
      - httpApi:
          path: /user/{id}
          method: put
          authorizer:
            name: cognitoAuth
  
  # DELETE (Protected)
  deleteUser:
    handler: src/handlers/deleteUser.handler
    events:
      - httpApi:
          path: /user/{id}
          method: delete
          authorizer:
            name: cognitoAuth
  
  # SQS Worker for User Created Events
  userCreatedWorker:
    handler: src/handlers/events/userCreated.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UserSignupQueue
              - Arn

resources:
  Resources:
    UserSignupQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: UserSignupQueue

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
