service: aws-learning
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /
          method: get
